Repository mj610-kim/excellent-code, pull requests merged in 2022-03, with the labels that each got.

#8 Feature/project setup
  .gitignore
  EmployeeManagementSystem/.gradle/7.1/dependencies-accessors/dependencies-accessors.lock
  EmployeeManagementSystem/.gradle/7.1/dependencies-accessors/gc.properties
  EmployeeManagementSystem/.gradle/7.1/executionHistory/executionHistory.bin
  EmployeeManagementSystem/.gradle/7.1/executionHistory/executionHistory.lock
  EmployeeManagementSystem/.gradle/7.1/fileChanges/last-build.bin
  EmployeeManagementSystem/.gradle/7.1/fileHashes/fileHashes.bin
  EmployeeManagementSystem/.gradle/7.1/fileHashes/fileHashes.lock
  EmployeeManagementSystem/.gradle/7.1/gc.properties
  EmployeeManagementSystem/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  EmployeeManagementSystem/.gradle/buildOutputCleanup/cache.properties
  EmployeeManagementSystem/.gradle/buildOutputCleanup/outputFiles.bin
  EmployeeManagementSystem/.gradle/checksums/checksums.lock
  EmployeeManagementSystem/.gradle/vcs-1/gc.properties
  EmployeeManagementSystem/.idea/compiler.xml
  EmployeeManagementSystem/.idea/gradle.xml
  EmployeeManagementSystem/.idea/jarRepositories.xml
  EmployeeManagementSystem/.idea/misc.xml
  EmployeeManagementSystem/.idea/vcs.xml
  EmployeeManagementSystem/.idea/workspace.xml
  EmployeeManagementSystem/build.gradle
  EmployeeManagementSystem/build/tmp/compileJava/previous-compilation-data.bin
  EmployeeManagementSystem/build/tmp/jar/MANIFEST.MF
  EmployeeManagementSystem/gradle/wrapper/gradle-wrapper.properties
  EmployeeManagementSystem/gradlew
  EmployeeManagementSystem/gradlew.bat
  EmployeeManagementSystem/settings.gradle
  EmployeeManagementSystem/src/main/java/Main.java
Labels: enhancement

#10 build: change JDK version to 8
  EmployeeManagementSystem/.idea/misc.xml
  EmployeeManagementSystem/.idea/workspace.xml
Labels: bug

#11 test: add ExampleTest
  EmployeeManagementSystem/.idea/misc.xml
  EmployeeManagementSystem/.idea/uiDesigner.xml
  EmployeeManagementSystem/.idea/workspace.xml
  EmployeeManagementSystem/build.gradle
  EmployeeManagementSystem/src/test/java/ExampleTest.java
Labels: enhancement

#13 Feature/gitignore
  .gitignore
  EmployeeManagementSystem/.gradle/7.1/dependencies-accessors/dependencies-accessors.lock
  EmployeeManagementSystem/.gradle/7.1/dependencies-accessors/gc.properties
  EmployeeManagementSystem/.gradle/7.1/executionHistory/executionHistory.bin
  EmployeeManagementSystem/.gradle/7.1/executionHistory/executionHistory.lock
  EmployeeManagementSystem/.gradle/7.1/fileChanges/last-build.bin
  EmployeeManagementSystem/.gradle/7.1/fileHashes/fileHashes.bin
  EmployeeManagementSystem/.gradle/7.1/fileHashes/fileHashes.lock
  EmployeeManagementSystem/.gradle/7.1/gc.properties
  EmployeeManagementSystem/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  EmployeeManagementSystem/.gradle/buildOutputCleanup/cache.properties
  EmployeeManagementSystem/.gradle/buildOutputCleanup/outputFiles.bin
  EmployeeManagementSystem/.gradle/checksums/checksums.lock
  EmployeeManagementSystem/.gradle/vcs-1/gc.properties
  EmployeeManagementSystem/.idea/gradle.xml
  EmployeeManagementSystem/.idea/uiDesigner.xml
  EmployeeManagementSystem/.idea/workspace.xml
  EmployeeManagementSystem/build/tmp/compileJava/previous-compilation-data.bin
  EmployeeManagementSystem/build/tmp/jar/MANIFEST.MF
Labels: bug

#6 docs: add README.md
  README.md
Labels: documentation

#14 fix: change languageLevel JDK from 15 to 8
  EmployeeManagementSystem/.idea/misc.xml
Labels: bug

#15 Feature/gitignore
  .gitignore
  EmployeeManagementSystem/.idea/compiler.xml
  EmployeeManagementSystem/.idea/jarRepositories.xml
  EmployeeManagementSystem/.idea/misc.xml
Labels: bug

#16 [build] Add build dependency for Mockito
  EmployeeManagementSystem/build.gradle
  EmployeeManagementSystem/src/test/java/ExampleTest.java
Labels: enhancement

#17 Feature/test code inputreader outputwriter
  EmployeeManagementSystem/build.gradle
  EmployeeManagementSystem/src/main/java/InputReader.java
  EmployeeManagementSystem/src/main/java/LocalFileReader.java
  EmployeeManagementSystem/src/test/java/ExampleTest.java
  EmployeeManagementSystem/src/test/java/LocalFileReaderTest.java
Labels: enhancement

#18 Feature, test: Implement test code for Option Handler
  EmployeeManagementSystem/src/main/java/BirthDayComparable.java
  EmployeeManagementSystem/src/main/java/BirthMonthComparable.java
  EmployeeManagementSystem/src/main/java/BirthYearComparable.java
  EmployeeManagementSystem/src/main/java/Employee.java
  EmployeeManagementSystem/src/main/java/Filter.java
  EmployeeManagementSystem/src/main/java/FirstNameComparable.java
  EmployeeManagementSystem/src/main/java/LastNameComparable.java
  EmployeeManagementSystem/src/main/java/LastNumberComparable.java
  EmployeeManagementSystem/src/main/java/MiddleNumberComparable.java
  EmployeeManagementSystem/src/main/java/Option1.java
  EmployeeManagementSystem/src/main/java/Option2.java
  EmployeeManagementSystem/src/test/java/OptionHandlerTest.java
Labels: enhancement

#19 test: add LocalFileWriterTest
  EmployeeManagementSystem/src/main/java/LocalFileWriter.java
  EmployeeManagementSystem/src/main/java/OutputWriter.java
  EmployeeManagementSystem/src/test/java/LocalFileReaderTest.java
  EmployeeManagementSystem/src/test/java/LocalFileWriterTest.java
Labels: enhancement

#24 feat: implement LocalFileReader
  EmployeeManagementSystem/src/main/java/LocalFileReader.java
Labels: enhancement

#25 feat: implement LocalFileWriter
  EmployeeManagementSystem/src/main/java/LocalFileWriter.java
Labels: enhancement

#29 Feature/test code database
  EmployeeManagementSystem/src/main/java/Database.java
  EmployeeManagementSystem/src/test/java/DatabaseTest.java
Labels: enhancement

#30 feat: Add Command Parser and Command Parser Test classes
  EmployeeManagementSystem/src/main/java/CommandParser.java
  EmployeeManagementSystem/src/main/java/Employee.java
  EmployeeManagementSystem/src/test/java/CommandParserTest.java
Labels: enhancement

#31 feature, test: add all columns to isMatched, modColumn. change add pa…
  EmployeeManagementSystem/src/main/java/Database.java
  EmployeeManagementSystem/src/test/java/DatabaseTest.java
Labels: enhancement

#34 refactor: Add Employee~Filter classes
  EmployeeManagementSystem/src/main/java/EmployeeBirthDayFilter.java
  EmployeeManagementSystem/src/main/java/EmployeeFilter.java
  EmployeeManagementSystem/src/main/java/EmployeeNameFilter.java
  EmployeeManagementSystem/src/main/java/EmployeePhoneNumFilter.java
  EmployeeManagementSystem/src/main/java/Option1.java
  EmployeeManagementSystem/src/main/java/Option2.java
  EmployeeManagementSystem/src/main/java/OptionHandler.java
  EmployeeManagementSystem/src/test/java/OptionHandlerTest.java
Labels: refactoring

#35 refactoring: Add static/final keyward to variable
  EmployeeManagementSystem/src/main/java/EmployeeBirthDayFilter.java
  EmployeeManagementSystem/src/main/java/EmployeeNameFilter.java
  EmployeeManagementSystem/src/main/java/EmployeePhoneNumFilter.java
  EmployeeManagementSystem/src/main/java/Option2.java
Labels: refactoring

#36 refactor: update code to follow code style guidelines
  EmployeeManagementSystem/src/main/java/BirthDayComparable.java
  EmployeeManagementSystem/src/main/java/BirthMonthComparable.java
  EmployeeManagementSystem/src/main/java/BirthYearComparable.java
  EmployeeManagementSystem/src/main/java/CommandParser.java
  EmployeeManagementSystem/src/main/java/Database.java
  EmployeeManagementSystem/src/main/java/Employee.java
  EmployeeManagementSystem/src/main/java/EmployeeBirthDayFilter.java
  EmployeeManagementSystem/src/main/java/EmployeeFilter.java
  EmployeeManagementSystem/src/main/java/EmployeeNameFilter.java
  EmployeeManagementSystem/src/main/java/EmployeePhoneNumFilter.java
  EmployeeManagementSystem/src/main/java/Filter.java
  EmployeeManagementSystem/src/main/java/FirstNameComparable.java
  EmployeeManagementSystem/src/main/java/LastNameComparable.java
  EmployeeManagementSystem/src/main/java/LastNumberComparable.java
  EmployeeManagementSystem/src/main/java/MiddleNumberComparable.java
  EmployeeManagementSystem/src/main/java/Option1.java
  EmployeeManagementSystem/src/main/java/Option2.java
  EmployeeManagementSystem/src/main/java/OptionHandler.java
  EmployeeManagementSystem/src/test/java/DatabaseTest.java
Labels: refactoring

#40 bug fix: handle null option in Option2.processOption()
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/optionhandler/Option1.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/optionhandler/Option2.java
  EmployeeManagementSystem/src/test/java/com/cra08/excellentcode/optionhandler/OptionHandlerTest.java
Labels: bug

#42 test : add test scenario for OptionHandler class
  EmployeeManagementSystem/src/test/java/com/cra08/excellentcode/optionhandler/OptionHandlerTest.java
Labels: enhancement

#48 feature: add sort employee database by employeeNum
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/storage/Database.java
  EmployeeManagementSystem/src/test/java/com/cra08/excellentcode/storage/DatabaseModTest.java
  EmployeeManagementSystem/src/test/java/com/cra08/excellentcode/storage/DatabaseSchTest.java
  EmployeeManagementSystem/src/test/java/com/cra08/excellentcode/storage/DatabaseSortTest.java
  EmployeeManagementSystem/src/test/java/com/cra08/excellentcode/storage/DatabaseTest.java
Labels: enhancement

#47 bugfix : modified output string format(remove \n)
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/optionhandler/Option1.java
  EmployeeManagementSystem/src/test/java/com/cra08/excellentcode/optionhandler/OptionHandlerTest.java
Labels: bug

#49 Feature/implement commandhandler
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/CommandHandler.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/Main.java
Labels: enhancement

#50 bugfix : swap first name and last name
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/Employee.java
Labels: bug

#52 fix: modify ColumnBirthday.java contains method and add input.txt
  EmployeeManagementSystem/input.txt
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/column/ColumnBirthday.java
Labels: bug

#60 Feature/apply coding style
  EmployeeManagementSystem/.idea/codeStyles/codeStyleConfig.xml
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/CommandHandler.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/CommandParser.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/column/ColumnBirthday.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/column/ColumnCerti.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/column/ColumnCl.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/column/ColumnEmployeeNum.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/column/ColumnName.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/column/ColumnPhoneNum.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/optionhandler/Option1.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/optionhandler/Option2.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/optionhandler/OptionHandler.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/storage/Database.java
  README.md
Labels: refactoring

#57 build: remove mockito-junit-jupiter dependency
  EmployeeManagementSystem/build.gradle
Labels: refactoring

#59 Feature/update documentation
  README.md
Labels: documentation

#61 Feature/update gitignore
  .gitignore
  EmployeeManagementSystem/input.txt
Labels: refactoring

#62 Feature/refactor commandhandler
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/CommandHandler.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/Main.java
Labels: refactoring

#63 Feature/refactor commandParser
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/CommandParser.java
  EmployeeManagementSystem/src/test/java/CommandParserTest.java
Labels: refactoring

#69 fix: fix wrong arguments in optionHandler#processOptions at handleModCmd
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/CommandHandler.java
Labels: bug

#66 refactor: add singleton pattern to column module
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/CommandHandler.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/column/ColumnBirthday.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/column/ColumnCerti.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/column/ColumnCl.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/column/ColumnEmployeeNum.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/column/ColumnName.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/column/ColumnPhoneNum.java
Labels: refactoring

#70 Feature/integration test
  .github/workflows/integration-test.yml
  EmployeeManagementSystem/build.gradle
  EmployeeManagementSystem/input_20_20.txt
  EmployeeManagementSystem/input_mj.txt
  EmployeeManagementSystem/input_sj.txt
  EmployeeManagementSystem/output_expected_20_20.txt
  EmployeeManagementSystem/output_expected_mj.txt
  EmployeeManagementSystem/output_expected_sj.txt
Labels: enhancement

#72 fix: fix sort bug about substring and compareTo
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/storage/Database.java
  EmployeeManagementSystem/src/test/java/com/cra08/excellentcode/storage/DatabaseSortTest.java
Labels: bug

#76 Bugfix/contains to equals
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/column/ColumnBirthday.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/column/ColumnCerti.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/column/ColumnCl.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/column/ColumnEmployeeNum.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/column/ColumnName.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/column/ColumnPhoneNum.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/column/IColumn.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/storage/Database.java
  EmployeeManagementSystem/src/test/java/com/cra08/excellentcode/storage/DatabaseModTest.java
  EmployeeManagementSystem/src/test/java/com/cra08/excellentcode/storage/DatabaseSchTest.java
  EmployeeManagementSystem/src/test/java/com/cra08/excellentcode/storage/DatabaseTest.java
Labels: bug

#73 ci: add test case
  .github/workflows/integration-test.yml
  EmployeeManagementSystem/input_hj.txt
  EmployeeManagementSystem/input_sj.txt
  EmployeeManagementSystem/input_tm.txt
  EmployeeManagementSystem/output_expected_hj.txt
  EmployeeManagementSystem/output_expected_tm.txt
Labels: enhancement

#81 docs: update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#74 Feature/refactoring and clean code option
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/CommandHandler.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/datatype/Cmd.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/option/BirthDayOption.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/option/BirthMonthOption.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/option/BirthYearOption.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/option/EmptyOption.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/option/FirstNameOption.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/option/IOption.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/option/LastNameOption.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/option/LastNumberOption.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/option/MiddleNumberOption.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/option/PrintOption.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/optionhandler/BirthDayComparable.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/optionhandler/BirthMonthComparable.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/optionhandler/BirthYearComparable.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/optionhandler/EmployeeBirthDayFilter.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/optionhandler/EmployeeFilter.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/optionhandler/EmployeeNameFilter.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/optionhandler/EmployeePhoneNumFilter.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/optionhandler/FirstNameComparable.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/optionhandler/LastNameComparable.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/optionhandler/LastNumberComparable.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/optionhandler/MiddleNumberComparable.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/optionhandler/Option1.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/optionhandler/Option2.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/optionhandler/OptionHandler.java
  EmployeeManagementSystem/src/test/java/com/cra08/excellentcode/optionhandler/OptionHandlerTest.java
Labels: enhancement

#75 test: add test case for IO module
  EmployeeManagementSystem/src/test/java/com/cra08/excellentcode/io/LocalFileReaderTest.java
  EmployeeManagementSystem/src/test/java/com/cra08/excellentcode/io/LocalFileWriterTest.java
Labels: enhancement

#87 refactor: modify the isValidCommand to take cmd Enum instead of command array list
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/CommandParser.java
Labels: enhancement

#86 Feature/refactor
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/CommandParser.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/datatype/Cmd.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/option/BirthDayOption.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/option/BirthMonthOption.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/option/BirthYearOption.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/option/EmptyOption.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/option/FirstNameOption.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/option/LastNameOption.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/option/LastNumberOption.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/option/MiddleNumberOption.java
  EmployeeManagementSystem/src/main/java/com/cra08/excellentcode/option/PrintOption.java
  EmployeeManagementSystem/src/test/java/CommandParserTest.java
  EmployeeManagementSystem/src/test/java/com/cra08/excellentcode/optionhandler/OptionHandlerTest.java
Labels: refactoring

#84 docs: add code of conduct
  .github/CODE_OF_CONDUCT.md
Labels: documentation
